apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: jpardo-skillz/backstage
spec:
  type: service
  lifecycle: unknown
  owner: jpardo-skillz
